### ISSUE TITLE
Can't install off main due to axes module error

### ISSUE THREAD

**Issue by jondkelley** [ayushsaxenagithub/PilotLMS#2]
**Describe the bug**
Happens after successfully installing requirements.txt. It looks like axes is a dynamically loaded module of some sort that hasn't been committed yet. 

**To Reproduce**

```
PilotLMS$ python3 manage.py migrate
Traceback (most recent call last):
  File "/Users/toor/workspace/PilotLMS/manage.py", line 22, in <module>
    main()
  File "/Users/toor/workspace/PilotLMS/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/toor/workspace/PilotLMS/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/toor/workspace/PilotLMS/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/Users/toor/workspace/PilotLMS/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/toor/workspace/PilotLMS/venv/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/toor/workspace/PilotLMS/venv/lib/python3.9/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/local/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'axes'
```

**Comment by jondkelley** [comment]
This error goes away on the latest release 1.0.0 so must have been something new committed.

**Comment by Bigben83** [comment]
This still seems to be an issue on the main 1.0.0 release. 

Also python needs to be updated to python3,  I used the following
```apt-get install -y python-is-python3```

This is the error shown when running
```python manage.py migrate```

```
Traceback (most recent call last):
  File "/var/www/html/PilotLMS/manage.py", line 22, in <module>
    main()
  File "/var/www/html/PilotLMS/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'axes'
```
